---
  #  ansible-playbook -i hosts.txt --limit=201 add_user.yml -e "user=test password=1234567"
- hosts: all
  become: yes
  become_method: sudo
  vars:
    password: "test"
    user: "test"
    become_root: False
  tasks:
    - include: common/add_user.yml